name: Publish

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: takumi3488/cookiejar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata (writer)
        id: meta-writer
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-writer

      - name: Build and push Docker image (writer)
        id: build-and-push-writer
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-writer:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}-writer:latest
          labels: ${{ steps.meta-writer.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: writer

      - name: Extract Docker metadata (reader)
        id: meta-reader
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-reader

      - name: Build and push Docker image (reader)
        id: build-and-push-reader
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}-reader:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_NAME }}-reader:latest
          labels: ${{ steps.meta-reader.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          target: reader

  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Buf
        uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1
        with:
          setup_only: true

      - name: Push to Buf Registry
        run: buf push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
